name: GitHub Actions Demo
on:
#  push:
#    branches: 
#      - main
#    paths-ignore: 
#      - .github
#  pull_request:
#    branches: 
#      - main
#  schedule:
#    - cron: '15 6 * * SUN'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: 'environment on which to display'
  
# Just a comment to try
jobs:
  Build:
    name: The build job
    runs-on: ubuntu-latest
    steps:
       - run: |
            echo "toto ${{ github.event_name }}"
            echo "toto ${{ github.ref }}"
       - uses: actions/checkout@v4.1.1
       - run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
           echo "::notice file=./hol/02-My-first-action.md,line=6,endLine=8,title=Markdown is weird::The markdown looks weird here"
  Test:
    name: Tests
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [Build]
    steps: 
    - run: |
        echo "Testing"
  Load-Test:
    name: Load Tests
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - run: |
          echo "Testing"
          sleep 15
  DeployProd:
    name: Deploy prod
    if: github.event.inputs.environment == 'Production'
    runs-on: ubuntu-latest
    needs: 
      - Test
      - Load-Test
    steps:
      - run: |
          echo "Step 1."
          sleep 10
      - run: |
          echo "Step 2."
          sleep 10
  
