name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github
  pull_request:
    branches: 
      - main
#  schedule:
#    - cron: '15 6 * * SUN'
  workflow_dispatch:
  
# Just a comment to try
jobs:
  Build:
    name: The build job
    runs-on: ubuntu-latest
    steps:
       - run: |
            echo "toto ${{ github.event_name }}"
            echo "toto ${{ github.ref }}"
       - uses: actions/checkout@v4.1.1
       - run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
         
      
      
    
    
